language: java
script:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn compile war:war -f appapi/pom.xml

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on: master
  
